version: "2"

services:
  
  mongo-graylog:
    image: "mongo:3"
    volumes:
      - mongo:/data/db
      
  elasticsearch-graylog:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      
  graylog:
    image: marcusrickert/docker-graylog:2.2.1-1
    volumes:
      - graylog-journal:/usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://localhost:8050/api/
      TARGET_USERNAME: graylog
      TARGET_UID: 840
      TARGET_GROUPNAME: graylog
      TARGET_GID: 840
      
    depends_on:
      - mongo-graylog
      - elasticsearch-graylog
    links:
      - "elasticsearch-graylog:elasticsearch"
      - "mongo-graylog:mongo"
    ports:
      - "8051:9000"
      - "12202/udp:12201/udp"
      - "1515/udp:1514/udp"

volumes:
  elasticsearch:
  graylog-journal:
  mongo:
        